[Unit]
After=smart-trolley-zenoh-router.service
Wants=smart-trolley-zenoh-router.service

[Service]
Environment=RMW_IMPLEMENTATION=rmw_zenoh_cpp
Environment=AMENT_PREFIX_PATH=/home/josemsotov/ros_zenoh_overlay/root/opt/ros/jazzy:/opt/ros/jazzy
Environment=LD_LIBRARY_PATH=/home/josemsotov/ros_zenoh_overlay/root/opt/ros/jazzy/lib:/home/josemsotov/ros_zenoh_overlay/root/opt/ros/jazzy/opt/zenoh_cpp_vendor/lib:/opt/ros/jazzy/lib:/opt/ros/jazzy/lib/aarch64-linux-gnu
Environment=ZENOH_ROUTER_CHECK_ATTEMPTS=0
