cmake_minimum_required(VERSION 3.8)
project(kinect_ros2)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(FREENECT REQUIRED libfreenect)
add_executable(kinect_node src/kinect_node.cpp)
target_include_directories(kinect_node PRIVATE ${FREENECT_INCLUDE_DIRS})
target_link_libraries(kinect_node ${FREENECT_LIBRARIES} freenect_sync)
ament_target_dependencies(kinect_node rclcpp sensor_msgs)
install(TARGETS kinect_node DESTINATION lib/${PROJECT_NAME})
ament_package()
