<?xml version="1.0"?>
<package format="3">
  <name>robot_operator_web</name>
  <version>1.0.0</version>
  <description>Web operator interface for the Smart Trolley ROS 2 stack.</description>
  <maintainer email="josemsotov@example.com">josemsotov</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
